try {
    let a=[1,2,3,4,5]
    console.log(a[6])
} catch (error) {
    console.error(error)
}finally{
    console.log("finally")
}